package com.comptalapin.persistence;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseManager {
    private static final String DEFAULT_DB_URL = "jdbc:hsqldb:file:comptalapin_db;shutdown=true";
    private static final String DB_USER = "SA";
    private static final String DB_PASSWORD = "";

    /**
     * System property key to override the DB URL.
     * Set to a unique in-memory URL (e.g. "jdbc:hsqldb:mem:testdb_123") for test isolation.
     */
    private static final String DB_URL_PROPERTY = "comptalapin.db.url";

    private static DatabaseManager instance;
    private Connection connection;

    private DatabaseManager() {
        try {
            String dbUrl = System.getProperty(DB_URL_PROPERTY, DEFAULT_DB_URL);
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            connection = DriverManager.getConnection(dbUrl, DB_USER, DB_PASSWORD);
            initSchema();
        } catch (ClassNotFoundException | SQLException e) {
            throw new RuntimeException("Failed to initialize database", e);
        }
    }

    public static DatabaseManager getInstance() {
        if (instance == null) {
            instance = new DatabaseManager();
        }
        return instance;
    }

    public Connection getConnection() {
        return connection;
    }

    private void initSchema() throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute(
                "CREATE TABLE IF NOT EXISTS ACCOUNT (" +
                "  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  NAME VARCHAR(100) NOT NULL," +
                "  INITIAL_BALANCE DECIMAL(15,2) DEFAULT 0 NOT NULL" +
                ")"
            );
            stmt.execute(
                "CREATE TABLE IF NOT EXISTS QUARTER (" +
                "  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  YEAR INT NOT NULL," +
                "  NUMBER INT NOT NULL," +
                "  STATUS VARCHAR(10) DEFAULT 'OPEN' NOT NULL" +
                ")"
            );
            stmt.execute(
                "CREATE TABLE IF NOT EXISTS OPERATION (" +
                "  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  OP_DATE DATE NOT NULL," +
                "  DESCRIPTION VARCHAR(200)," +
                "  AMOUNT DECIMAL(15,2) NOT NULL," +
                "  TYPE VARCHAR(10) NOT NULL," +
                "  ACCOUNT_ID BIGINT NOT NULL," +
                "  TARGET_ACCOUNT_ID BIGINT," +
                "  QUARTER_ID BIGINT NOT NULL," +
                "  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)," +
                "  FOREIGN KEY (TARGET_ACCOUNT_ID) REFERENCES ACCOUNT(ID)," +
                "  FOREIGN KEY (QUARTER_ID) REFERENCES QUARTER(ID)" +
                ")"
            );
            connection.commit();
        }
    }

    public void shutdown() {
        try {
            if (connection != null && !connection.isClosed()) {
                try (Statement stmt = connection.createStatement()) {
                    stmt.execute("SHUTDOWN");
                }
                connection.close();
            }
        } catch (SQLException e) {
            // ignore on shutdown
        }
    }

    /** Reset the singleton — for testing only. */
    public static void resetInstance() {
        if (instance != null) {
            instance.shutdown();
            instance = null;
        }
    }
}
